import { Router } from 'next/dist/client/router'
import Head from 'next/head'
import React, { FC, useEffect, useState } from 'react'
import { Aside } from './aside/aside.component'
import { MainContent } from './layout.styled'
import { Nav } from './nav/nav.component'

export const Layout: FC<{router: Router}> = ({ children, router }) => {

    const [sideWidth, setSideWidth] = useState(60) // estado que define el ancho del sidebar
    const [position, setPosition] = useState(0) // posicion del dragger del sidebar

    // Colapsar o desplegar la navegacion lateral
    const toggleAside = () => {
        setSideWidth(prev => prev < 70 ? 280 : 60)
        setPosition(prev => prev < 70 ? 0 : -220)
    }
    // Hacer resize de la navegacion al arrastrar
    const handleDragAside = (width: number) => {
        if(sideWidth + width < 60){ return }
        setSideWidth(prev => prev + width)
    }
    return (
        <>
            <Head>
                <title>{router.pathname.split('/')[1]}</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            {/* Navegacion lateral */}
            <Aside positionDragger={position} handleDragAside={handleDragAside} width={sideWidth}/>
            {/* Navegacion superior */}
            <Nav toggleAside={toggleAside} width={sideWidth}/>
            {/* Contenido de la pagina */}
            <MainContent width={sideWidth}>
                { children }
            </MainContent>
        </>
    )
}
