import { FC, useState } from 'react'
import { Router } from 'next/dist/client/router'
import { Aside } from './aside/aside.component'
import { MainContent } from './layout.styled'
import { Nav } from './nav/nav.component'
import Head from 'next/head'

export const Layout: FC<{router: Router}> = ({ children, router }) => {
  const [sideWidth, setSideWidth] = useState(60) // estado que define el ancho del sidebar

  // Colapsar o desplegar la navegacion lateral
  const toggleAside = () => {
    setSideWidth(prev => prev < 70 ? 280 : 60)
  }

  return (
        <>
            <Head>
                <title>{router.pathname.split('/')[1]}</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Aside width={sideWidth}/>
            <Nav toggleAside={toggleAside} width={sideWidth}/>
            <MainContent width={sideWidth}>
                { children }
            </MainContent>
        </>
  )
}
