import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'

const Index: NextPage = () => {
  return (

        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Link href='/home'>Inicio</Link>
            <br />
            <Link href='/example'>Pagina de ejemplo</Link>
        </>
  )
}

export default Index
