import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'

const Index: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/home">Casa</Link>
    </>
  )
}

export default Index
